/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef WEBVIEW_AUTODEFS_H
#define WEBVIEW_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_WEBVIEW_NAME "WebView"
#define S3E_EXT_WEBVIEW_HASH 0xbedac4de

#endif /* !WEBVIEW_AUTODEFS_H */
